IEI-122058 - Improve audit / syslog thread naming and handling
dcm4che/dcm4che pull request #1235
Opened 2022-07-21 13:32 UTC by zliang88

Added NamedThreadFactory and thread pool to audit syslog

2022-07-21 15:01 UTC, alan-farquhar commented on dcm4che-net-audit/src/main/java/org/dcm4che3/net/audit/SyslogProtocolHandler.java
> -                    LOG.info("Received Syslog message of {} bytes from {}",
Please restore the log.info messages we shouldn't be changing these to debug in dcm4che master.

2022-07-21 15:02 UTC, alan-farquhar requested changes
undo log.debug to restore these back to log.info

2022-07-21 15:16 UTC, alan-farquhar approved these changes

2022-07-22 12:49 UTC, gunterze requested changes
Rejected, because it introduces an additional, not customizable Thread-pool.
Suggest to just provide a static setter to overwrite the use of device.executor by another executor of your choice:
```java
    private static volatile Executor executor;

    public static void setExecutor(Executor executor) {
        SyslogProtocolHandler.executor = executor;
    }

    @Override
    public void onAccept(Connection conn, Socket s) {
        if (executor != null)
            executor.execute(new SyslogReceiverTLS(conn, s));
        else
            conn.getDevice().execute(new SyslogReceiverTLS(conn, s));
    }

    @Override
    public void onReceive(Connection conn, DatagramPacket packet) {
        if (executor != null)
            executor.execute(new SyslogReceiverUDP(conn, packet));
        else
            conn.getDevice().execute(new SyslogReceiverUDP(conn, packet));
    }
```

2022-07-22 16:11 UTC, gunterze approved these changes

2022-07-26 12:17 UTC, merged